In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_excel(r"D:\Customer A & R\data\raw\raw_large_user_data.xlsx")

In [3]:
data.head()

,Customer ID,Subscription Length (Months),Customer Satisfaction Score (1-10),Daily Watch Time (Hours),Engagement Rate (1-10),Device Used Most Often,Genre Preference,Region,Payment History (On-Time/Delayed),Subscription Plan,Churn Status (Yes/No),Support Queries Logged,Age,Monthly Income ($),Promotional Offers Used,Number of Profiles Created
0,C00001,12,10,4.85,4,Tablet,Action,Europe,On-Time,Basic,No,10,33,6250,5,2
1,C00002,12,8,1.75,9,Laptop,Thriller,Europe,On-Time,Basic,Yes,9,28,7018,1,5
2,C00003,3,4,2.75,9,Smart TV,Comedy,Asia,On-Time,Premium,Yes,3,18,1055,1,5
3,C00004,3,7,3.00,9,Smart TV,Drama,Europe,Delayed,Premium,No,5,32,6707,5,4
4,C00005,24,2,1.37,5,Mobile,Drama,North America,On-Time,Standard,Yes,2,59,1506,3,5

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         1000 non-null   str
 1   Subscription Length (Months)        1000 non-null   int64
 2   Customer Satisfaction Score (1-10)  1000 non-null   int64
 3   Daily Watch Time (Hours)            1000 non-null   float64
 4   Engagement Rate (1-10)              1000 non-null   int64
 5   Device Used Most Often              1000 non-null   str
 6   Genre Preference                    1000 non-null   str
 7   Region                              1000 non-null   str
 8   Payment History (On-Time/Delayed)   1000 non-null   str
 9   Subscription Plan                   1000 non-null   str
 10  Churn Status (Yes/No)               1000 non-null   str
 11  Support Queries Logged              1000 non-null   int64
 12  Age                                 1000 non-null   int64
 13  Monthly Income ($)                  1000 non-null   int64
 14  Promotional Offers Used             1000 non-null   int64
 15  Number of Profiles Created          1000 non-null   int64
dtypes: float64(1), int64(8), str(7)
memory usage: 125.1 KB

In [5]:
data.isnull().sum()

Customer ID                           0
Subscription Length (Months)          0
Customer Satisfaction Score (1-10)    0
Daily Watch Time (Hours)              0
Engagement Rate (1-10)                0
Device Used Most Often                0
Genre Preference                      0
Region                                0
Payment History (On-Time/Delayed)     0
Subscription Plan                     0
Churn Status (Yes/No)                 0
Support Queries Logged                0
Age                                   0
Monthly Income ($)                    0
Promotional Offers Used               0
Number of Profiles Created            0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.drop_duplicates(inplace=True)

In [8]:
data.columns = [
    "Customer_ID",
    "Subscription_Length",
    "Customer_Satisfaction",
    "Daily_Watch_Time",
    "Engagement_Rate",
    "Device",
    "Genre",
    "Region",
    "Payment_History",
    "Subscription_Plan",
    "Churn",
    "Support_Queries",
    "Age",
    "Monthly_Income",
    "Promotional_Offers",
    "Profiles_Created"
]

In [9]:
data.dtypes

Customer_ID                  str
Subscription_Length        int64
Customer_Satisfaction      int64
Daily_Watch_Time         float64
Engagement_Rate            int64
Device                       str
Genre                        str
Region                       str
Payment_History              str
Subscription_Plan            str
Churn                        str
Support_Queries            int64
Age                        int64
Monthly_Income             int64
Promotional_Offers         int64
Profiles_Created           int64
dtype: object

In [10]:
for col in data.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(data[col].unique())

Customer_ID
<StringArray>
['C00001', 'C00002', 'C00003', 'C00004', 'C00005', 'C00006', 'C00007',
 'C00008', 'C00009', 'C00010',
 ...
 'C00991', 'C00992', 'C00993', 'C00994', 'C00995', 'C00996', 'C00997',
 'C00998', 'C00999', 'C01000']
Length: 1000, dtype: str

Device
<StringArray>
['Tablet', 'Laptop', 'Smart TV', 'Mobile', 'Desktop']
Length: 5, dtype: str

Genre
<StringArray>
['Action', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Sci-Fi', 'Documentary']
Length: 7, dtype: str

Region
<StringArray>
['Europe', 'Asia', 'North America', 'Africa', 'South America']
Length: 5, dtype: str

Payment_History
<StringArray>
['On-Time', 'Delayed']
Length: 2, dtype: str

Subscription_Plan
<StringArray>
['Basic', 'Premium', 'Standard']
Length: 3, dtype: str

Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

C:\Users\Admin\AppData\Local\Temp\ipykernel_18380\2075428814.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in data.select_dtypes(include="object").columns:

In [11]:
for col in data.select_dtypes(include="object").columns:
    data[col] = data[col].str.strip()

C:\Users\Admin\AppData\Local\Temp\ipykernel_18380\3560895772.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in data.select_dtypes(include="object").columns:

In [12]:
days = []

for index, row in data.iterrows():

    if row["Churn"] == "Yes":

        if row["Daily_Watch_Time"] < 2:
            days.append(random.randint(45, 90))

        else:
            days.append(random.randint(30, 60))

    else:

        if row["Daily_Watch_Time"] > 4:
            days.append(random.randint(0, 10))

        else:
            days.append(random.randint(10, 30))

data["Days_Since_Last_Activity"] = days

In [13]:
data.head()

,Customer_ID,Subscription_Length,Customer_Satisfaction,Daily_Watch_Time,Engagement_Rate,Device,Genre,Region,Payment_History,Subscription_Plan,Churn,Support_Queries,Age,Monthly_Income,Promotional_Offers,Profiles_Created,Days_Since_Last_Activity
0,C00001,12,10,4.85,4,Tablet,Action,Europe,On-Time,Basic,No,10,33,6250,5,2,4
1,C00002,12,8,1.75,9,Laptop,Thriller,Europe,On-Time,Basic,Yes,9,28,7018,1,5,71
2,C00003,3,4,2.75,9,Smart TV,Comedy,Asia,On-Time,Premium,Yes,3,18,1055,1,5,50
3,C00004,3,7,3.00,9,Smart TV,Drama,Europe,Delayed,Premium,No,5,32,6707,5,4,10
4,C00005,24,2,1.37,5,Mobile,Drama,North America,On-Time,Standard,Yes,2,59,1506,3,5,59

In [14]:
data.shape

(1000, 17)

In [15]:
data.isnull().sum()

Customer_ID                 0
Subscription_Length         0
Customer_Satisfaction       0
Daily_Watch_Time            0
Engagement_Rate             0
Device                      0
Genre                       0
Region                      0
Payment_History             0
Subscription_Plan           0
Churn                       0
Support_Queries             0
Age                         0
Monthly_Income              0
Promotional_Offers          0
Profiles_Created            0
Days_Since_Last_Activity    0
dtype: int64

In [16]:
data.to_csv("../data/processed/cleaned.csv", index=False)

In [17]:
cleaned_data = pd.read_csv("../data/processed/cleaned.csv")

cleaned_data.head()

,Customer_ID,Subscription_Length,Customer_Satisfaction,Daily_Watch_Time,Engagement_Rate,Device,Genre,Region,Payment_History,Subscription_Plan,Churn,Support_Queries,Age,Monthly_Income,Promotional_Offers,Profiles_Created,Days_Since_Last_Activity
0,C00001,12,10,4.85,4,Tablet,Action,Europe,On-Time,Basic,No,10,33,6250,5,2,4
1,C00002,12,8,1.75,9,Laptop,Thriller,Europe,On-Time,Basic,Yes,9,28,7018,1,5,71
2,C00003,3,4,2.75,9,Smart TV,Comedy,Asia,On-Time,Premium,Yes,3,18,1055,1,5,50
3,C00004,3,7,3.00,9,Smart TV,Drama,Europe,Delayed,Premium,No,5,32,6707,5,4,10
4,C00005,24,2,1.37,5,Mobile,Drama,North America,On-Time,Standard,Yes,2,59,1506,3,5,59

In [18]:
cleaned_data = pd.read_csv("../data/processed/cleaned.csv")

cleaned_data.head()

,Customer_ID,Subscription_Length,Customer_Satisfaction,Daily_Watch_Time,Engagement_Rate,Device,Genre,Region,Payment_History,Subscription_Plan,Churn,Support_Queries,Age,Monthly_Income,Promotional_Offers,Profiles_Created,Days_Since_Last_Activity
0,C00001,12,10,4.85,4,Tablet,Action,Europe,On-Time,Basic,No,10,33,6250,5,2,4
1,C00002,12,8,1.75,9,Laptop,Thriller,Europe,On-Time,Basic,Yes,9,28,7018,1,5,71
2,C00003,3,4,2.75,9,Smart TV,Comedy,Asia,On-Time,Premium,Yes,3,18,1055,1,5,50
3,C00004,3,7,3.00,9,Smart TV,Drama,Europe,Delayed,Premium,No,5,32,6707,5,4,10
4,C00005,24,2,1.37,5,Mobile,Drama,North America,On-Time,Standard,Yes,2,59,1506,3,5,59